config/routes.rb
Cookbook::Application.routes.draw do
  match 'recipes/all' => 'recipes#all', :as => :all_recipes
  match 'recipes/search' => 'recipes#search', :as => :search_recipes
  resources :recipes

  match 'login/index' => 'login#index', :as => :login
  match 'login/attempt_login' => 'login#attempt_login'
  match 'logout' => 'login#logout'

  root :to => "recipes#index"
end

app/models/float.rb
class Float
  def number_decimal_places
    self.to_s.length - 2
  end

  def to_fraction
    higher = 10 ** self.number_decimal_places
    lower = self * higher

    gcd = _greatest_common_divisor(higher, lower)

    return (lower / gcd).round, (higher / gcd).round
  end

  def _greatest_common_divisor(a, b)
     while a % b != 0
       a, b = b.round, (a % b).round
     end
     b
  end
end

app/models/ingredient.rb
require "float"

class Ingredient < ActiveRecord::Base
  belongs_to :recipe

  def self.parse(str, recipe)
    result = Ingredient.new(:recipe_id => recipe.id, :quantity => 0)
    IngredientParser.new(str, result).parse
  end

  def display_string
    display = [quantity_as_fraction, uom, ingredient].compact.join(" ")
    display << ", #{instruction}" unless instruction.blank?
    display
  end

  def quantity_as_fraction
    the_quantity = self.quantity.to_i == 0 ? "" : "#{self.quantity.to_i} "
    the_quantity << fractional_part_of_quantity_as_fraction if fractional_part_of_quantity > 0
    return the_quantity.strip
  end

  def fractional_part_of_quantity
    return self.quantity - self.quantity.to_i
  end

  def fractional_part_of_quantity_as_fraction
    the_fraction = fractional_part_of_quantity.to_fraction
    return "#{the_fraction[0]}/#{the_fraction[1]}"
  end
end

app/models/ingredient_parser.rb
class IngredientParser

  def initialize(str, ingredient)
    @tokens = str.split
    @result = ingredient
    @state = :quantity
    @ingredient_words = []
    @instruction_words = []
  end

  UNITS = %w{ cups pounds ounces tablespoons teaspoons cans cloves }

  def parse
    @tokens.each do |token|
      redo unless self.send(@state, token)
    end

    @result.ingredient = @ingredient_words.join(" ")
    @result.instruction = @instruction_words.join(" ")
    @result
  end

  def quantity(token)
    if token.include?("/")
      numerator, denominator = token.split("/")
      fraction = Rational(numerator.to_i, denominator.to_i)
      @result.quantity += fraction.to_f
    elsif token.to_f > 0
      @result.quantity += token.to_f
    end

    @state = :uom
  end

  def uom(token)
    if is_a_number?(token)
      @state = :quantity
      return false
    else
      @state = :ingredient
      if is_a_unit?(token)
        @result.uom = token.pluralize
        return true
      else
        return false
      end
    end
  end

  def ingredient(token)
    @ingredient_words << token

    if is_start_of_instructions?(token)
      chop_last_ingredient
      @state = :instruction
    end
    return true
  end

  def instruction(token)
    @instruction_words << token
  end

  def is_a_number?(token)
    return token.to_i > 0
  end

  def is_a_unit?(token)
    return UNITS.include?(token) || UNITS.include?(token.pluralize)
  end

  def is_start_of_instructions?(token)
    return token.ends_with?(",")
  end

  def chop_last_ingredient
    @ingredient_words.last.chop!
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :ingredients

  def self.search_clause
    return searchable_fields.map {|a| "#{a} LIKE ?"}.join(" OR ")
  end

  def self.searchable_fields
    return ["title", "preparation", "source"]
  end

  def belongs_to_user?(user_id)
    return self.user_id.to_s == user_id.to_s
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes, :order => "title"

  validates_presence_of     :login, :email, :password, :password_confirmation, :salt
  validates_uniqueness_of   :login, :email
  validates_format_of       :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_length_of       :password, :minimum => 6
  validates_confirmation_of :password

  attr_accessor :password, :password_confirmation

  def password=(password)
    @password = password
    self.salt = (0..25).inject('') { |r, i| r << rand(93) + 33 }
    self.hashed_password = User.encrypt(@password, self.salt)
  end

  def self.authenticate(login, password)
    user = find(:first, :conditions => ["login = ?", login])
    return nil if user.nil?
    return user if User.encrypt(password, user.salt) == user.hashed_password
    return nil
  end

  def self.encrypt(password, salt)
    Digest::SHA1.hexdigest("#{password}#{salt}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def attempt_login
    if @user = User.authenticate(params[:user], params[:password])
      session[:user_id] = @user.id
      redirect_to :controller => "recipes", :action => "index"
    else
      flash[:error] = "Invalid username or password."
      redirect_to :controller => "login", :action => "index"
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to :controller => "login", :action => "index"
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :secure_page

  def index
    @recipes = user_recipes
  end

  def all
    @recipes = Recipe.find(:all, :order => "title")
    render :template => "recipes/index"
  end

  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.iphone do
        render :layout => false
      end
      format.html do
        render :template => "recipes/show"
      end
    end
  end

  def new
    @recipe = user_recipes.build
  end

  def create
    begin
      @recipe = user_recipes.build(params[:recipe])
      @recipe.save!
      flash[:message] = "Successfully created recipe"
      redirect_to :action => "index"
    rescue ActiveRecord::RecordInvalid
      render :template => "recipes/new", :layout => false
    end
  end

  def edit
    begin
      @recipe = user_recipes.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render :template => "recipes/not_found"
    end
  end

  def update
    @recipe = user_recipes.find(params[:id])
    if @recipe.update_attributes(params[:recipe])
      flash[:message] = "Successfully updated recipe"
      redirect_to :action => "index"
    else
      render :template => "recipes/edit"
    end
  end

  def destroy
    begin
      @recipe = user_recipes.find(params[:id])
      if @recipe.destroy
        flash[:message] = "Successfully deleted recipe"
        redirect_to :action => "index"
      end
    rescue ActiveRecord::RecordNotFound
      render :template => "recipes/not_found"
    end
  end

  def search
    @recipes = user_recipes.find(:all, :conditions => [Recipe.search_clause, "%#{params[:query]}%", "%#{params[:query]}%", "%#{params[:query]}%"])
    render :template => "recipes/index"
  end

  private

  def secure_page
    if session[:user_id].nil?
      redirect_to :controller => "login", :action => "index"
    else
      @user = User.find(session[:user_id])
    end
  end

  def user_recipes
    return @user.recipes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def iphone_user_agent?(request)
    return true if request.user_agent =~ /(Mobile\/.+Safari)/
    return false
  end

  def logged_in?
    return true if session[:user_id]
    return false
  end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Cookbook</title>
    <%= stylesheet_link_tag 'document' %>
    <%= stylesheet_link_tag 'ingrid' %>
    <%= javascript_include_tag 'prototype' %>
    <%= javascript_include_tag 'rails' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div role="document" id="doc" class="ingrid in-fourths">
      <header>
        <h1>Cookbook</h1>
      </header>
      <div id="sidebar" class="unit">
        <% if logged_in? -%>
          <ul>
            <li><%= link_to "My Recipes", recipes_url %></li>
            <li><%= link_to "All Recipes", all_recipes_url %></li>
            <li><%= link_to "New Recipe", new_recipe_url %></li>
            <li><%= link_to "Logout", logout_url %></li>
          </ul>
        <% end -%>
      </div>
      <div class="unit span-three">
        <%= render :partial => "shared/flash", :locals => {:flash => flash} %>
        <%= yield %>
        <footer>
          <div class="credits">Copyright &copy;<%= Date.today.year %></div>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/login/index.html.erb
<%= form_tag "attempt_login" do %>
	<div id="login_panel">
		<table width="40%">
			<tr>
				<td><%= label_tag "user", "Username:" %></td>
				<td><%= text_field_tag "user" %></td>
			</tr>
			<tr>
				<td><%= label_tag "password", "Password:" %></td>
				<td><%= password_field_tag "password" %></td>
			</tr>
			<tr>
				<td colspan="2">&nbsp;</td>
			</tr>
			<tr>
				<td colspan="2" align="right"><%= submit_tag "Login", :id => "login"%></td>
			</tr>
		</table>
	</div>
<% end -%>

app/views/recipes/_form.html.erb
<%= label(:recipe, :title)%>: <%= form.text_field :title %><br />
<%= label(:recipe, :bake_temperature) %>: <%= form.text_field :bake_temperature %><br />
<%= label(:recipe, :prep_time) %>: <%= form.text_field :prep_time %><br />
<%= label(:recipe, :cook_time_hours) %>: <%= form.text_field :cook_time_hours %><br />
<%= label(:recipe, :cook_time_minutes) %>: <%= form.text_field :cook_time_minutes %><br />
<%= label(:recipe, :preparation) %>: <%= form.text_area :preparation %><br />
<%= label(:recipe, :yield) %>: <%= form.text_field :yield %><br />
<%= label(:recipe, :source) %>: <%= form.text_field :source %><br />
<%= label(:recipe, :image_url) %>: <%= form.text_field :image_url %><br />

app/views/recipes/edit.html.erb
<%= form_for @recipe do |form| -%>
	<%= render :partial => 'recipes/form', :locals => {:form => form} %>
	<%= link_to "Cancel", recipe_path(@recipe) %>
  <%= submit_tag 'Update' %>
<% end %>

app/views/recipes/index.html.erb
<% if flash[:notice] -%>
	<div class="flash"><%= flash[:notice] %></div>
<% end -%>

<div id="recipe_search">
	<%= form_tag('recipes/search') do %>
		<%= text_field_tag "query", nil, :size => 40 %>
		<%= submit_tag "Search" %>
	<% end %>
</div>

<div id="recipe_list">
	<ul>
		<% if @recipes.empty? -%>
		  <li>No Recipes Found</li>
		<% else -%>
  		<% @recipes.each do |recipe| -%>
  			<li><%= link_to recipe.title, recipe_path(recipe) %></li>
  		<% end -%>
		<% end -%>
	</ul>
</div>

app/views/recipes/new.html.erb
<%= form_for @recipe do |form| -%>
	<%= render :partial => 'recipes/form', :locals => { :form => form } %>
  <%= link_to "Cancel", recipes_path %>
  <%= form.submit 'Create' %>
<% end %>

app/views/recipes/not_found.html.erb
<h2>The recipe you requested was not found, or is not yours.</h2>

app/views/recipes/show.html.erb
<h2><%= @recipe.title %></h2>

<div>
	<table>
		<tr>
			<td>Source:</td>
			<td><%= @recipe.source %></td>
		</tr>
		<tr>
			<td>Yield:</td>
			<td><%= @recipe.yield %></td>
		</tr>
		<tr>
			<td>Prep Time:</td>
			<td><%= @recipe.prep_time %> minutes</td>
		</tr>
		<tr>
			<td>Cook Time:</td>
			<td><%= @recipe.cook_time_hours %> hours <%= @recipe.cook_time_minutes.to_i %> minutes</td>
		</tr>
	</table>
</div>

<h3>Preparation</h3>
<div>
  <% @recipe.preparation.to_s.split("\n").each do |paragraph| -%>
    <p><%= paragraph %></p>
  <% end -%>
</div>

<% if @recipe.belongs_to_user?(session[:user_id]) -%>
  <div id="recipe_links">
  	<%= link_to "Edit Recipe", {:controller => "recipes", :action => "edit", :id => @recipe.id } %> &nbsp; | &nbsp;
  	<%= link_to "Delete Recipe", @recipe, :confirm => "Are you sure?", :method => :delete %>
  </div>
<% end -%>

app/views/shared/_flash.html.erb
<% for name in [:warning, :message, :error] -%>
	<% if flash[name] -%>
		<div id="<%=name%>" class="flash"><%=flash[name]%></div>
	<% end -%>
<% end -%>